services:

  db-test:
    image: postgres:15-alpine
    env_file: .env.test
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U testuser -d testdb" ]
      interval: 2s
      timeout: 5s
      retries: 10


  tests:
    build: .
    env_file: .env.test
    command: .venv/bin/pytest -v tests/
    environment:
      - APP_DB_DRIVER=postgresql+asyncpg
      - APP_DB_HOST=db-test
      - APP_DB_PORT=5432
      - APP_DB_USER=testuser
      - APP_DB_PASSWORD=testpass
      - APP_DB_NAME=testdb

    depends_on:
      db-test:
        condition: service_healthy
